import auth from './auth-routes';
import componentPatterns from './component-patterns-routes';
import countries from './countries-routes';
import definitions from './definitions-routes';
import fields from './fields-routes';
import menu from './menus-routes';
import pageAttributeTypes from './page-attribute-types-routes';
import pageDetails from './page-details-routes';
import pageStructure from './page-structure-routes';
import pageTemplates from './page-templates-routes';
import pageTypes from './page-types-routes';
import pages from './pages-routes';
import siteInfo from './site-info-routes';
import stats from './stats-routes';
import users from './users-routes';

export default app => {
  app.use('/v1', auth);
  app.use('/v1', componentPatterns);
  app.use('/v1', countries);
  app.use('/v1', definitions);
  app.use('/v1', fields);
  app.use('/v1', menu);
  app.use('/v1', pageAttributeTypes);
  app.use('/v1', pageDetails);
  app.use('/v1', pageStructure);
  app.use('/v1', pageTemplates);
  app.use('/v1', pageTypes);
  app.use('/v1', pages);
  app.use('/v1', siteInfo);
  app.use('/v1', stats);
  app.use('/v1', users);
};
